version: 0.2

phases:
  build:
    commands:
      - echo "Launching ECS Task to run Terraform"
      - |
        aws ecs run-task \
          --cluster ${ECS_CLUSTER_NAME} \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[${SUBNET_ID}],securityGroups=[${SECURITY_GROUP_ID}],assignPublicIp=ENABLED}" \
          --task-definition ${TASK_DEFINITION_NAME} \
          --region ${AWS_REGION}
