notification_email        = "arbieto.jc@gmail.com"
pipeline_role_arn         = "arn:aws:iam::123456789012:role/codepipeline-role"
github_owner              = "JulioCesarArbieto"
github_repo               = "nombre-del-repo"
github_branch             = "main"
github_token              = "ghp_XXXXXXXXXXXXXXXXXXXXXX"